version: '3'
services:

  mysql:
    image: "mysql:8.0"
    command: mysqld --sql_mode="" --character-set-server=utf8mb4 --collation-server=utf8mb4_bin 
    restart: on-failure
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "6677"
      MYSQL_DATABASE: "zac"
    volumes: 
      - "./data:/var/lib/mysql:rw"   
      